### PR TITLE
DOCS-1949: Review constrain motion tutorial

### PR DESCRIPTION
**Pull request by sguequierre**
Idk why I felt the need to edit the commented out frame section as well -- @JessamyT is there a reason that part would be readded or could I delete it?

### CODE REVIEW

**Comment by JessamyT** [comment]
Ooh great question--I *think* it was because the frame visualization stuff was maybe going through some revamping and we didn't want to showcase the current state of it at the time? The thought was to go back and revise this part once the visualizer was improved or debugged or something? Not sure what the status of it is now...

**Comment by sguequierre** [comment]
> Ooh great question--I _think_ it was because the frame visualization stuff was maybe going through some revamping and we didn't want to showcase the current state of it at the time? The thought was to go back and revise this part once the visualizer was improved or debugged or something? Not sure what the status of it is now...

lol as of R2D2 the visualizer is like totally not functioning... it will likely not be functioning still at time of release bc the feature is not as widely used. so just going to leave commented for now

**Comment by JessamyT** [comment]
> > Ooh great question--I _think_ it was because the frame visualization stuff was maybe going through some revamping and we didn't want to showcase the current state of it at the time? The thought was to go back and revise this part once the visualizer was improved or debugged or something? Not sure what the status of it is now...
> 
> lol as of R2D2 the visualizer is like totally not functioning... it will likely not be functioning still at time of release bc the feature is not as widely used. so just going to leave commented for now

Sounds good to me. That part of the tutorial is as you can see very non-critical so there's no rush whatsoever to un-comment it.

**Review by JessamyT — APPROVED** [review]
LGTM!

**Pull request merged**
