### PR TITLE
DOCS-1867: Specify SQL dialect

### PR DESCRIPTION
**Pull request by andf-viam**
Per ticket ask: Clarify which flavor of SQL data query supports (Atlas SQL) and bring MQL reference link to top of this page.

### CODE REVIEW

**Comment by andf-viam** [comment]
Hi @dmhilly , updated per ticket ask -- LMK if you'd like to see any changes, thaks!

**Review by npentrel — APPROVED** [review]
Feel free to merge. If @dmhilly has more feedback we can open a new ticket

**Review by dmhilly — APPROVED** [review]
LGTM!

Apologies for the delay; I was OOO Thursday and Friday.

**Comment by andf-viam** [comment]
@dmhilly Thank you, no worries of course.

**Pull request merged**
