### PR TITLE
Update edit button

### PR DESCRIPTION
**Pull request by npentrel**
I'm not sure how I feel about this but people frequently miss this so I thought a less subtle approach might help.

### CODE REVIEW

**Review by sguequierre — COMMENTED** [review]
I think a little bit too big

**Comment by andf-viam** [comment]
Ok by me! Or: maybe just a little smaller -- it is rather bolded as-is anyways.

**Comment by npentrel** [comment]
updated to make the icon smaller. The text is at the standard text size, smaller would look odd compared to the other text

**Review by andf-viam — APPROVED** [review]
LGTM!

**Review by sguequierre — APPROVED** [review]

**Pull request merged**
