### PR TITLE
DOCS-2620: rm join-color-depth

### PR DESCRIPTION
**Pull request by andf-viam**
Remove `join_color_depth` model from docs.

### CODE REVIEW

**Comment by andf-viam** [comment]
@hexbabe Removed from the docs! LMK if you want to see any other changes, thanks!

**Comment by hexbabe** [comment]
The diff looks good! Not sure why when I use https://docs-test.viam.dev/3101 I still see the page though...

**Review by hexbabe — APPROVED** [review]

**Comment by andf-viam** [comment]
@hexbabe Hmm, where do you see it? `NoSuchKey ` here: https://docs-test.viam.dev/3101/components/camera/join-color-depth/. Does it pop up somewhere else that I missed?

**Comment by hexbabe** [comment]
I saw it using the search bar querying “join color”

**Comment by hexbabe** [comment]
Got it. Makes sense that search results come from staging

**Pull request merged**
