### PR TITLE
DOCS-1752: Capitalize CONTROL and LOGS tabs across docs

### PR DESCRIPTION
**Pull request by sguequierre**

### CODE REVIEW

**Review by andf-viam — APPROVED** [review]
LGTM with one thought:

Do you have a preference on whether you want tab UI names that are part of links to be bolded as well? You've inherited both here:

- `[CONTROL tab](/fleet/machines/#control)`
- `[**CONTROL** tab](/fleet/machines/#control)`

Same with LOGS. This seems like the perfect opportunity to pick one and update the rest. I am fine with either, just that they be consistent. Do you have a preference?

**Comment by sguequierre** [comment]
> LGTM with one thought:
> 
> Do you have a preference on whether you want tab UI names that are part of links to be bolded as well? You've inherited both here:
> 
> * `[CONTROL tab](/fleet/machines/#control)`
> * `[**CONTROL** tab](/fleet/machines/#control)`
> 
> Same with LOGS. This seems like the perfect opportunity to pick one and update the rest. I am fine with either, just that they be consistent. Do you have a preference?

I don't have a strong preference but I suppose maybe bold in links? Will update!

**Comment by sguequierre** [comment]
> LGTM with one thought:
> 
> Do you have a preference on whether you want tab UI names that are part of links to be bolded as well? You've inherited both here:
> 
> * `[CONTROL tab](/fleet/machines/#control)`
> * `[**CONTROL** tab](/fleet/machines/#control)`
> 
> Same with LOGS. This seems like the perfect opportunity to pick one and update the rest. I am fine with either, just that they be consistent. Do you have a preference?

updated!

**Review by andf-viam — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
