### PR TITLE
DOCS-933: Add image of detection bounding boxes to detections page

### PR DESCRIPTION
**Pull request by JessamyT**

### CODE REVIEW

**Comment by npentrel** [comment]
There is good but I was also hoping for one at the bottom before the code section where we instruct people to go to the control tab. And we probably want the same for classifications

**Review by sguequierre — APPROVED** [review]
LGTM (oops, once naomi's comments are addressed)!

**Comment by JessamyT** [comment]
Looks like we already have one on the classifications page. It'd be nice to have one for segmentation, but I don't have a 3D camera set up. Do we have any good images around?

**Comment by npentrel** [comment]
Please ask the vision team if they have something for the segmenter page

**Comment by JessamyT** [comment]
Realized there's not actually a good place to put the image for segmentation right now, so created https://viam.atlassian.net/browse/DOCS-975, and maybe adding that image can be part of that ticket instead of this one?

**Review by npentrel — APPROVED** [review]

**Pull request merged**
