### PR TITLE
RSDK-8119 - delete velodyne builtin docs

### PR DESCRIPTION
**Pull request by seanavery**
We are removing the builtin velodyne camera component -- this PR simply removes refs from the documentation.

### CODE REVIEW

**Comment by seanavery** [comment]
@npentrel Any tips on removing `velodyne` option return on the supported models section? It is still showing up after removing the component page. 
https://docs.viam.com/components/camera/

**Comment by npentrel** [comment]
I'm not at my computer you'd need to delete the velodyne.md file and then upon deploy it should be gone. I can do it tmrw morning

**Review by npentrel — APPROVED** [review]
Thank you!

**Comment by npentrel** [comment]
@seanavery Velodyne is now gone - thanks!

**Pull request merged**
