### PR TITLE
fixing incorrect image

### PR DESCRIPTION
**Pull request by ariellemella**
published image includes robot secret, fixing to correct image from draft

### CODE REVIEW

**Comment by andf-viam** [comment]
Agreed with the spirit of this change, but that's not currently where the **Copy** button lives any longer.  Here's current, feel free to use this image if you agree!

**Comment by andf-viam** [comment]
Better pic!

**Comment by ariellemella** [comment]
thanks @andf-viam for the suggested change! I didn't even know the ui changed again xD

**Review by andf-viam — APPROVED** [review]
LGTM, thanks much!

**Review by andf-viam — APPROVED** [review]
LGTM, thanks much!

**Comment by npentrel** [comment]
Merging on your behalf @ariellemella

**Pull request merged**
