### PR TITLE
typo fix (expressif -> espressif)

### PR DESCRIPTION
**Pull request by paulmand3l**
# Description

Fixing mispelling of Espressif's name.

### CODE REVIEW

**Comment by paulmand3l** [comment]
Looks like there's one more I can't fix in the source code here: https://docs.viam.com/installation/prepare/

**Review by sguequierre — APPROVED** [review]
Thank you for catching this!

**Comment by paulmand3l** [comment]
What do I need to become a member of to resolve the failing check?

**Comment by sguequierre** [comment]
> What do I need to become a member of to resolve the failing check?

That check is asking if you are a member of the @viamrobotics organization! I can merge this branch for you, will do so now.

**Comment by paulmand3l** [comment]
Thanks!

**Pull request merged**
